/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.view;

import com.company.helper.DBConnection;
import com.company.helper.Helper;
import com.company.model.Doctor;
import com.company.model.Patient;
import com.company.model.Surgeon;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Eminov
 */
public class LoginGUI extends javax.swing.JFrame {

    private DBConnection db = DBConnection.instance();

    /**
     * Creates new form Login
     */
    public LoginGUI() {
        initComponents();
        Helper.centerWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        w_tabpane = new javax.swing.JTabbedPane();
        pnlpatient = new javax.swing.JPanel();
        lblpatientid = new javax.swing.JLabel();
        lblpatientpass = new javax.swing.JLabel();
        txtpatientid = new javax.swing.JTextField();
        btnpatientin = new javax.swing.JButton();
        btnpatientup = new javax.swing.JButton();
        txtpatientpass = new javax.swing.JPasswordField();
        pnldoctor = new javax.swing.JPanel();
        lbldoctorid = new javax.swing.JLabel();
        lbldoctorpass = new javax.swing.JLabel();
        txtdoctorid = new javax.swing.JTextField();
        btndoctor = new javax.swing.JButton();
        txtdoctorpass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("welcome to hospital system");
        lblWelcome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 135, 319, 24));

        pnlpatient.setBackground(new java.awt.Color(0, 153, 255));

        lblpatientid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblpatientid.setText("Username");

        lblpatientpass.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblpatientpass.setText("Password");

        btnpatientin.setBackground(new java.awt.Color(204, 204, 204));
        btnpatientin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnpatientin.setText("Sign in");
        btnpatientin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnpatientin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientinActionPerformed(evt);
            }
        });

        btnpatientup.setBackground(new java.awt.Color(204, 204, 204));
        btnpatientup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnpatientup.setText("Sign up");
        btnpatientup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnpatientup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientupActionPerformed(evt);
            }
        });

        txtpatientpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlpatientLayout = new javax.swing.GroupLayout(pnlpatient);
        pnlpatient.setLayout(pnlpatientLayout);
        pnlpatientLayout.setHorizontalGroup(
            pnlpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpatientLayout.createSequentialGroup()
                .addGroup(pnlpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpatientLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pnlpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblpatientpass, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(lblpatientid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(pnlpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpatientid, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(txtpatientpass)))
                    .addGroup(pnlpatientLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnpatientin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnpatientup, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        pnlpatientLayout.setVerticalGroup(
            pnlpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpatientLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpatientid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpatientid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblpatientpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpatientpass, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlpatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpatientin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpatientup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        w_tabpane.addTab("patient account", pnlpatient);

        pnldoctor.setBackground(new java.awt.Color(0, 153, 153));

        lbldoctorid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbldoctorid.setText("Username");

        lbldoctorpass.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbldoctorpass.setText("Password");

        btndoctor.setBackground(new java.awt.Color(204, 204, 204));
        btndoctor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndoctor.setText("Sign in");
        btndoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnldoctorLayout = new javax.swing.GroupLayout(pnldoctor);
        pnldoctor.setLayout(pnldoctorLayout);
        pnldoctorLayout.setHorizontalGroup(
            pnldoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldoctorLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnldoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btndoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnldoctorLayout.createSequentialGroup()
                        .addGroup(pnldoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbldoctorpass, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(lbldoctorid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(pnldoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdoctorid, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(txtdoctorpass))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        pnldoctorLayout.setVerticalGroup(
            pnldoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldoctorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnldoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdoctorid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldoctorid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnldoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldoctorpass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdoctorpass, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btndoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        w_tabpane.addTab("doctor account", pnldoctor);

        jPanel2.add(w_tabpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 186, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/abc.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 11, 113, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoctorActionPerformed
        // TODO add your handling code here:
        if (txtdoctorid.getText().length() == 0 || txtdoctorpass.getText().length() == 0) {
            Helper.showMsg("fill");
        } else {
            boolean found = false;
            try {
                Connection c = db.dbConn();
                Statement stmt = c.createStatement();
                ResultSet rs = stmt.executeQuery("select * from User");
                while (rs.next()) {
                    if (txtdoctorid.getText().equals(rs.getString("username")) && txtdoctorpass.getText().equals(rs.getString("password"))) {
                        found = true;
                        if (rs.getString("type").equals("surgeon")) {
                            Surgeon surgeon = new Surgeon();
                            surgeon.setId(rs.getInt("id"));
                            surgeon.setUsername(rs.getString("username"));
                            surgeon.setPassword(rs.getString("password"));
                            surgeon.setName(rs.getString("name"));
                            surgeon.setType(rs.getString("type"));

                            SurgeonGUI sGUI = new SurgeonGUI(surgeon);
                            sGUI.setVisible(true);
                            dispose(); // bu frame i bagla.
                        }

                        if (rs.getString("type").equals("doctor")) {
                            Doctor doctor = new Doctor();
                            doctor.setId(rs.getInt("id"));
                            doctor.setUsername(rs.getString("username"));
                            doctor.setPassword(rs.getString("password"));
                            doctor.setName(rs.getString("name"));
                            doctor.setType(rs.getString("type"));

                            DoctorGUI dGUI = new DoctorGUI(doctor);
                            dGUI.setVisible(true);
                            dispose(); // bu frame i bagla.

                        }
                    }

                }
                if (!found) {
                    Helper.showMsg("Username or password is invalid ");
                    txtdoctorpass.setText(null);
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btndoctorActionPerformed

    private void btnpatientupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientupActionPerformed
        RegisterGUI register = new RegisterGUI();
        register.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnpatientupActionPerformed

    private void txtpatientpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientpassActionPerformed

    private void btnpatientinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientinActionPerformed
        if (txtpatientid.getText().length() == 0 || txtpatientid.getText().length() == 0) {
            Helper.showMsg("fill");
        } else {
            boolean found = false;
            try {
                Connection c = db.dbConn();
                Statement stmt = c.createStatement();
                ResultSet rs = stmt.executeQuery("select * from User");
                while (rs.next()) {
                    if (txtpatientid.getText().equals(rs.getString("username")) && txtpatientpass.getText().equals(rs.getString("password"))) {
                        found = true;
                        if (rs.getString("type").equals("patient")) {
                            Patient patient = new Patient();
                            patient.setId(rs.getInt("id"));
                            patient.setName(rs.getString("name"));
                            patient.setUsername(rs.getString("username"));
                            patient.setPassword(rs.getString("password"));
                            patient.setType(rs.getString("type"));

                            PatientGUI patientGUI = new PatientGUI(patient);
                            patientGUI.setVisible(true);
                            dispose();
                        }
                    }
                }
                if (!found) {
                    Helper.showMsg("Username or password is invalid ");
                    txtpatientpass.setText(null);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnpatientinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginGUI frame = new LoginGUI();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndoctor;
    private javax.swing.JButton btnpatientin;
    private javax.swing.JButton btnpatientup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lbldoctorid;
    private javax.swing.JLabel lbldoctorpass;
    private javax.swing.JLabel lblpatientid;
    private javax.swing.JLabel lblpatientpass;
    private javax.swing.JPanel pnldoctor;
    private javax.swing.JPanel pnlpatient;
    private javax.swing.JTextField txtdoctorid;
    private javax.swing.JPasswordField txtdoctorpass;
    private javax.swing.JTextField txtpatientid;
    private javax.swing.JPasswordField txtpatientpass;
    private javax.swing.JTabbedPane w_tabpane;
    // End of variables declaration//GEN-END:variables
}
